from __future__ import annotations

import json

from app.agents.base import BaseAgent
from app.models.state import TravelState


class FinalAdvisoryAgent(BaseAgent):
    name = "final_advisory_agent"
    purpose = "Synthesizes specialist outputs, surfaces conflicts, priorities and a final actionable advisory."

    async def analyze(self, state: TravelState):
        failed = [name for name, result in state.results.items() if result.status == "failed"]
        partial = [name for name, result in state.results.items() if result.status == "partial"]
        warnings = []
        if failed:
            warnings.append(f"Some specialist agents failed: {', '.join(failed)}")
        if partial:
            warnings.append(f"Some specialist outputs require verification: {', '.join(partial)}")

        top_actions = [
            "Confirm visa/entry/transit requirements from official sources before non-refundable commitments.",
            "Check the current official travel advisory and relevant public-health guidance.",
            "Book transport and lodging only after document feasibility is clear; preserve flexibility where practical.",
            "Refresh weather and local transport information close to departure and adapt the itinerary.",
            "Keep emergency contacts, insurance information, and offline document copies accessible.",
        ]

        compact = {
            name: {
                "status": result.status,
                "confidence": result.confidence,
                "data": result.data,
                "warnings": result.warnings,
            }
            for name, result in state.results.items()
            if name != self.name
        }
        try:
            narrative = await self.llm.generate(
                system=(
                    "You are the lead travel advisory orchestrator. Synthesize the specialist agent outputs into a concise, practical executive summary. "
                    "Resolve conflicts by preferring sourced structured data, preserve uncertainty, and never convert a verification task into an asserted legal/safety/health fact."
                ),
                user=json.dumps({"trip": state.request.model_dump(mode="json"), "agents": compact}, ensure_ascii=False, default=str),
            )
        except Exception as llm_exc:
            narrative = (
                f"Structured advisory completed for {state.request.destination}. "
                "Use the specialist sections below for itinerary, budget, weather, entry, safety, health, transport, accommodation, and packing. "
                "Complete all official-verification actions before relying on time-sensitive travel rules."
            )
            warnings.append(f"Lead LLM synthesis failed safely: {type(llm_exc).__name__}")
        data = {
            "executive_summary": narrative,
            "top_actions": top_actions,
            "day_by_day_itinerary": state.get_data("itinerary_agent").get("days", []),
            "budget": state.get_data("budget_agent"),
            "packing": state.get_data("packing_agent"),
            "entry_readiness": state.get_data("visa_entry_agent"),
            "safety": state.get_data("safety_agent"),
            "health": state.get_data("health_agent"),
            "weather": state.get_data("weather_agent"),
            "transport": state.get_data("transport_agent"),
            "accommodation": state.get_data("accommodation_agent"),
            "culture": state.get_data("local_etiquette_agent"),
            "agent_health": {
                "total_specialists": len(state.results),
                "failed": failed,
                "partial": partial,
            },
        }
        # Prevent BaseAgent from making a second LLM call for the final agent.
        data["ai_notes"] = "Final synthesis generated by the lead advisory agent."
        confidence_values = [r.confidence for r in state.results.values() if r.confidence > 0]
        confidence = sum(confidence_values) / len(confidence_values) if confidence_values else 0.5
        return data, warnings, [], round(confidence, 2)
